Issue 22 Tailwind and global styles
codersforcauses/wajo pull request #26
Opened 2024-12-10 02:57 UTC by ScottyTGB

## Change Summary

- Roboto and Urbanist now the primary fonts for Headings and body receptively.
- Font sizes changed for every tag from h1 through to h6 and other paragraph tags.
- Color palette added as custom palette in the tailwind config and global css.

### Change Form
N/A. I believe front end stuff doesn't require tests.

## Other Information
All styles have been applied with accordance of the current style sheet provided on [figma](https://www.figma.com/design/usGd8nihwCr6YPvzWi1YyR/WAJO?node-id=470-1865).

2024-12-10 04:08 UTC, ErikaKK commented on client/src/pages/index.tsx
Nice work. How about font styles for body?

2024-12-10 10:26 UTC, ScottyTGB commented on client/tailwind.config.ts
> +        yellow: "#ffd700",
I would require a second opinion on this one from the tech leads. I personally think adding identifiers in front of those names would be a bit finicky. For example writing bg-yellow-400 is a lot easier than bg-wajo-yellow-400. By doing `yellow: "#ffd700"` I've basically overridden Tailwind's default yellow of `yellow: "#facc15"`. So Tailwind's default yellow will never appear again, only ours. If I want to still use Tailwind's default yellow, only then I would distinguish them if it makes sense.

2024-12-11 07:08 UTC, ErikaKK commented on client/tailwind.config.ts
> +        yellow: "#ffd700",
I think you're right

2024-12-11 15:18 UTC, yunho7687 commented on client/tailwind.config.ts
> +        yellow: "#ffd700",
> I would require a second opinion on this one from the tech leads @AarifLamat @yunho7687 @Julie-Salazar. I personally think adding identifiers in front of those names would be a bit finicky. For example writing bg-yellow-400 is a lot easier than bg-wajo-yellow-400. By doing `yellow: "#ffd700"` I've basically overridden Tailwind's default yellow of `yellow: "#facc15"`. So Tailwind's default yellow will never appear again, only ours. If I want to still use Tailwind's default yellow, only then I would distinguish them if it makes sense.

yeah, good point, overwriting it is applicable in this project

2024-12-11 15:22 UTC, yunho7687 commented on client/package-lock.json
not sure why there's so many things changed here. what did you do for all these changes?  ngl, I am confused by these changes and not sure if there's any consequence once it's been changed

2024-12-11 15:40 UTC, yunho7687 requested changes
all in all, good job! will approve once figuring out the package-lock.json file

2024-12-11 15:40 UTC, yunho7687 commented on client/package-lock.json
@scratchclaggy yo, do you have any idea what kind of operation may lead to all these changes?

2024-12-12 08:31 UTC, ScottyTGB commented
> all in all, good job! will approve once figuring out the package-lock.json file

I can revert the package-lock.json if needed. All I did was `npm audit fix`.

2024-12-12 08:54 UTC, yunho7687 approved these changes
great job! thanks mate!

2024-12-12 08:55 UTC, yunho7687 commented
It can be merged now

2024-12-12 08:59 UTC, merged