Issue 15 create olympiad/quiz model
codersforcauses/wajo pull request #30
Opened 2024-12-11 08:57 UTC by thnorton

## Change Summary

Added Question and Category Models from latest db schema
Added a GET request for all questions and registered in django admin for testing
Please ignore the migrations, accidently commited them

2024-12-11 13:33 UTC, yunho7687 requested changes
well done! 
and here's the link for the [latest database design](https://dbdiagram.io/d/6757ff3ee9daa85aca394581) which has been settled

1. need to change the name of `Category` model to Question_category as per the new design
2. need to change some fields of them

2024-12-13 08:00 UTC, thnorton commented
updated the question and category model, also added image model

2024-12-14 04:49 UTC, yunho7687 requested changes
well done and need some changes for some fields

2024-12-14 04:49 UTC, yunho7687 commented on server/api/question/models.py
> +    time_created = models.DateTimeField(null=True, blank=True)
`from datetime import datetime`
`time_created =  datetime.datetime.now() `
here should be like this
reference: https://www.djangosnippets.org/snippets/1017/

2024-12-14 04:49 UTC, yunho7687 commented on server/api/question/models.py
> +    created_by = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='question_created')
related_name='question_created' it bette to be `questions_created`? how do you think of it?

2024-12-14 04:49 UTC, yunho7687 commented on server/api/question/models.py
> +    category_id = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
here need a related_name as well right?

2024-12-14 04:49 UTC, yunho7687 commented on server/api/question/models.py
> +    time_created = models.DateTimeField(null=True, blank=True)
whenever you see timestamp, it suggests that the field should be filled automatically.

2024-12-14 04:51 UTC, yunho7687 commented on server/api/question/models.py
> +    created_by = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='question_created')
question_text = models.TextField(default="set question text...") please put the default question text as ""( empty or null is a better choice I reckon.)

2025-01-08 04:18 UTC, yunho7687 approved these changes
well done!

2025-01-08 04:18 UTC, merged