Issue 7 Leaderboard Page
codersforcauses/wajo pull request #8
Opened 2024-11-26 16:31 UTC by loklokyx

## Change Summary
server:
- initial `app` directory, including migrations folder and base files for the route `/api/app/leaderboard/`

client:
- created basic UI with a simple `table`, `dropdown`, and `search`
- implemented search functionality with dropdown and input options
- added AJAX to retrieve BE sample data and search functionality in Leaderboard page `/admin/leaderboard`

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [Y] The pull request title has an issue number
- [Y] The change works by "Smoke testing" or quick testing
- [NA] The change has tests
- [NA] The change has documentation

## Other Information
server:
- temporarily use sample data before model creation for serialization
- permission validation is currently not implemented

client:
- pending layout implementation to merge Leaderboard body content

# Related issue

- Resolve #7

2024-11-27 10:36 UTC, loklokyx commented
![image](https://github.com/user-attachments/assets/b912319a-0c19-4a88-b18e-ab6a2e17cca3)
This is the current UI of the Table and Search Form

2024-12-02 14:41 UTC, yunho7687 requested changes
Amazing works! 
Need to mind that we don't need a new app named "app". there's a app named app in penni repo cuz people misunderstood the objective of the django server, which should be an api server and had already been created as "api". you can take this repo as ref: https://github.com/codersforcauses/csf/tree/main/server

2024-12-02 15:01 UTC, yunho7687 commented
You can use code below to create a sub-app in Django:
```bash
cd api
django-admin startapp sub-app-name-such-as-auth
```
and don't forget to install the app in `INSTALLED_APPS`.    

Here's a ref to that
https://stackoverflow.com/questions/2862084/how-do-i-create-sub-applications-in-django

2024-12-04 06:03 UTC, loklokyx commented
Hi Team,

With the CFC standard, I’ve added JSDoc and pydoc comments to the manager module for better clarity and documentation. Please help review the changes and let me know if any adjustments are needed. 

Thanks!

2024-12-05 05:28 UTC, Julie-Salazar approved these changes
Awesome work lgtm, you do have an empty migrations folder but it is understandable given you have set this up, really appreciate the comment documentation 🙌 I'm good to approve this for now, @yunho7687 might have notes tho

2024-12-06 15:37 UTC, yunho7687 reviewed
**Legend work!** 
I’ve decided to hold off on this PR for now until we have a discussion about it in the next session.

2024-12-06 15:37 UTC, yunho7687 commented on client/src/hooks/use-fetch-data.ts
> + * A custom hook that fetches data from an API using the `useQuery` hook from `react-query`.
I think this is an excellent example of how to write documentation, and it's worth us all following as a standard.

2024-12-07 08:12 UTC, yunho7687 approved these changes

2024-12-07 08:12 UTC, merged